### ISSUE TITLE
value of BooleanField is cast to string

### ISSUE THREAD

**Issue by wengole** [funkybob/django-sniplates#29]
https://github.com/funkybob/django-sniplates/blob/master/sniplates/templatetags/sniplates.py#L350

This line here casts the value of a BooleanField to a string. This means if you try to do something like

```
<input type="checkbox"  {% if value %}checked{% endif %}>
```
it won't work as value will always evaluate to True.

Am I missing something here, or is this a bug?

**Comment by funkybob** [comment]
No, this is certainly a bug.  The force_text on the value has been a long source of pain.

Can you please try to work up a test case to demonstrate this?

**Comment by wengole** [comment]
@funkybob Thanks for your reply. I'll gladly write a test case and even a fix :smile: 

I'm wondering why you are doing all this value parsing rather than using the field's to_python() methods

**Comment by funkybob** [comment]
That is not value parsing... this code is only for rendering forms... submissions are still handled as always.

**Comment by funkybob** [comment]
The new pluggable-explosives branch addresses this separately by adding the ``raw_value`` value...

**Comment by sergei-maertens** [comment]
Should be covered and fixed by #38 now

**Comment by funkybob** [comment]
@wengole can you please test if 0.4.0 fixes this?

**Comment by wengole** [comment]
@funkybob No this isn't fixed.

value is of type SafeText therefore always evaluating to True when not an empty string.

**Comment by sergei-maertens** [comment]
You should probably be testing `raw_value` in your if statement :)
